run-tests:
  script:
    - make test
#
#
# .build-template: &build-template
#   image: docker:stable
#   needs:
#     - run-tests
#   services:
#     - docker:dind
#   before_script:
#     - docker && docker login --username allocateengineering --password $DOCKER_IO_TOKEN

