run-tests:
  image: alpine
  script:
    - apk add make
    - make test
#
#
# .build-template: &build-template
#   image: docker:stable
#   needs:
#     - run-tests
#   services:
#     - docker:dind
#   before_script:
#     - apk add make
#     - docker login --username allocateengineering --password $DOCKER_IO_TOKEN

